apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-order-service
  namespace: yahu
  labels:
    app: health-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-order-service
  template:
    metadata:
      labels:
        app: health-order-service
    spec:
      containers:
        - name: health-order-service
          image: yahurt/health-order-service:2.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8004
          envFrom:
            - configMapRef:
                name: health-order-service-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
