apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: health-service
  namespace: yahu
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - yahu

  selector:
    matchLabels:
      app: health-service

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s