apiVersion: batch/v1
kind: Job
metadata:
  name: health-auth-service-migration
  namespace: yahu
  labels:
    app: health-auth-service
    component: migration
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: health-auth-service
        component: migration
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migration
          image: yahurt/health-auth-service:1.0.0
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "migrate"]
          envFrom:
            - configMapRef:
                name: health-auth-service-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: password
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 192Mi
