apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-service
  namespace: yahu
  labels:
    app: health-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-service
  template:
    metadata:
      labels:
        app: health-service
    spec:
      containers:
        - name: health-service
          image: yahurt/health-service:4.0.0
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: health-service-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
