apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-service
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /health/
            pathType: Prefix
            backend:
              service:
                name: health-service
                port:
                  number: 80