apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-service
  namespace: yahu
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: health-auth-bff
                port:
                  number: 80
