apiVersion: batch/v1
kind: Job

metadata:
  name: health-service-migration
  namespace: yahu
  labels:
    app: health-service
    component: migration

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: health-service
        component: migration

    spec:
      restartPolicy: Never

      containers:
        - name: migration
          image: yahurt/health-service:3.0.0
          command:
            - npm
            - run
            - migrate

          envFrom:
            - configMapRef:
                name: health-service-config

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-credentials
                  key: password
