apiVersion: v1
kind: Secret

metadata:
  name: users-db-credentials
  namespace: yahu
  labels:
    app: health-service
    component: database

type: Opaque

stringData:
  username: "users"
  password: "password"
  postgres-password: "postgres-password"