apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: elasticsearch
  namespace: yahu
  labels:
    app: elasticsearch

spec:
  serviceName: elasticsearch-headless
  replicas: 1

  selector:
    matchLabels:
      app: elasticsearch

  template:
    metadata:
      labels:
        app: elasticsearch

    spec:
      securityContext:
        fsGroup: 1000

      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.19.19

          ports:
            - name: http
              containerPort: 9200

            - name: transport
              containerPort: 9300

          env:
            - name: discovery.type
              value: single-node

            - name: xpack.security.enabled
              value: "false"

            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m

          resources:
            requests:
              cpu: 250m
              memory: 1Gi

            limits:
              memory: 1536Mi

          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=1s
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data

  volumeClaimTemplates:
    - metadata:
        name: data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 5Gi
